### PR TITLE
Issue#28

### PR DESCRIPTION
**Pull request by nbuso**
Hi this is a simple modification to keep track of bytes offsets at parsing time, it's used to keep track of entry position in release files.
It's based on https://github.com/enasequence/sequencetools/pull/27#pullrequestreview-97525024 than let me know and I can try to rebase it on your master.

### CODE REVIEW

**Comment by kethireddy** [comment]
Hi Nicola,
Sorry about late response.
Current version of Flat File parser is implemented to parse the valid content and set it to the entry object.
I think, it would be nice to have separate version of parser for ebisearch and which can use sequencetools as dependency.

**Comment by nbuso** [comment]
I understand your point, nevertheless I need to modify the LineReader and I fear I need to copy/paste good part of the code to instantiate a different version of the LineReader. I will take a look and I will come back in case

**Comment by nbuso** [comment]
Hi Kethi,
just to better understand when you speak about valid content in the ENA releases which one do you mean? can we identify it in the release files?

Nicola

**Comment by snathanvj** [comment]
@nbuso I think this old and no longer required, can I close this.

**Comment by raskoleinonen** [comment]
Closing pull request.

**Pull request closed without merging**
